name: Build FastAPI

on:
  push

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[CI Skip]')"
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          cd backend/
          docker build \
          --build-arg MONGO_DB_NAME="${{ secrets.MONGO_DB_NAME }}" \
          --build-arg MONGO_URI="${{ secrets.MONGO_URI }}" \
          --build-arg GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
          --build-arg GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
          --build-arg ENCRYPTION_KEY="${{ secrets.ENCRYPTION_KEY }}" \
          --build-arg ALLOWED_DOMAINS="${{ secrets.ALLOWED_DOMAINS }}" \
          -t google-oauth:latest .
